// ═══════════════════════════════════════════════════════════════════════════════
// NORMS — Single source of truth for cephalometric reference norms
// All modules (constants.js, descriptive.js) MUST import from here.
// ═══════════════════════════════════════════════════════════════════════════════

export const DEFAULT_NORMS = {
  Steiner: {
    source: "Steiner, 1953 / Am J Orthod",
    population: "Caucasian (North American)",
    ageRange: "Adult",
    sex: "Pooled (male + female)",
    stratification: "Not stratified by age, sex, or ethnicity. Single adult value — do not apply to growing patients.",
    norms: [
      { label: "SNA", mean: 82, sd: 2, type: "angle" },
      { label: "SNB", mean: 80, sd: 2, type: "angle" },
      { label: "ANB", mean: 2, sd: 2, type: "angle" },
      { label: "SN-MP", mean: 32, sd: 2, type: "angle" },
      { label: "GoGn-SN", mean: 32, sd: 2, type: "angle" },
      { label: "SN-Occ", mean: 14, sd: 2, type: "angle" },
      { label: "U1-NA", mean: 22, sd: 2, type: "angle" },
      { label: "U1-NA-mm", mean: 4, sd: 2, type: "length" },
      { label: "L1-NB", mean: 25, sd: 2, type: "angle" },
      { label: "L1-NB-mm", mean: 4, sd: 2, type: "length" },
      { label: "Interincisal", mean: 131, sd: 5, type: "angle" },
      { label: "U1-L1", mean: 131, sd: 5, type: "angle" },
    ],
  },
  Ricketts: {
    source: "Ricketts, 1960 / Am J Orthod",
    population: "Caucasian (North American)",
    ageRange: "Mixed (growing and adult)",
    sex: "Pooled (male + female)",
    stratification: "Not stratified by age or sex in this table. Ricketts' original norms are age-stratified — verify against age-matched source.",
    norms: [
      { label: "Facial axis", mean: 90, sd: 3, type: "angle" },
      { label: "Facial depth", mean: 87, sd: 3, type: "angle" },
      { label: "Mandibular plane", mean: 26, sd: 4, type: "angle" },
      { label: "Lower facial height", mean: 47, sd: 4, type: "angle" },
      { label: "Mandibular arc", mean: 26, sd: 4, type: "angle" },
      { label: "Convexity", mean: 2, sd: 2, type: "length" },
      { label: "Interincisal", mean: 130, sd: 6, type: "angle" },
      { label: "U1-APog", mean: 28, sd: 4, type: "angle" },
      { label: "U1-APog-mm", mean: 3.5, sd: 2.5, type: "length" },
      { label: "L1-APog", mean: 22, sd: 4, type: "angle" },
      { label: "L1-APog-mm", mean: 1.5, sd: 2, type: "length" },
    ],
  },
  Downs: {
    source: "Downs, 1948 / Am J Orthod",
    population: "Caucasian (North American)",
    ageRange: "Adolescent (12-17y)",
    sex: "Pooled (male + female)",
    stratification: "Not stratified by age, sex, or ethnicity. Based on adolescent subjects — may not apply to adults.",
    norms: [
      { label: "Facial angle", mean: 87.8, sd: 3.6, type: "angle" },
      { label: "Convexity", mean: 0, sd: 5.9, type: "angle" },
      { label: "AB plane", mean: -4.6, sd: 3.7, type: "angle" },
      { label: "Mandibular plane", mean: 21.9, sd: 3.7, type: "angle" },
      { label: "Y-axis", mean: 59.4, sd: 3.8, type: "angle" },
      { label: "Occlusal plane", mean: 9.3, sd: 3.8, type: "angle" },
      { label: "Interincisal", mean: 135.4, sd: 5.8, type: "angle" },
      { label: "U1-L1", mean: 135.4, sd: 5.8, type: "angle" },
    ],
  },
  McNamara: {
    source: "McNamara, 1984 / Am J Orthod",
    population: "Caucasian (North American)",
    ageRange: "Mixed (children and adults, not separated)",
    sex: "Pooled (male + female)",
    stratification: "Not stratified in this table. McNamara's linear measurements are age/sex-stratified in the source — verify against age/sex-matched reference.",
    norms: [
      { label: "Maxillary Depth", mean: 90, sd: 3, type: "angle" },
      { label: "Facial Depth", mean: 88, sd: 3, type: "angle" },
      { label: "ANB", mean: 2, sd: 2, type: "angle" },
      { label: "Lower facial height", mean: 47, sd: 4, type: "angle" },
      { label: "N-A", mean: 1, sd: 2, type: "length" },
      { label: "N-B", mean: 4, sd: 3, type: "length" },
      { label: "A-N", mean: 1, sd: 2, type: "length" },
    ],
  },
  "Bjork-Jarabak": {
    source: "Jarabak, 1972",
    population: "Caucasian (Scandinavian)",
    ageRange: "Mixed (growing and adult)",
    sex: "Pooled (male + female)",
    stratification: "Not stratified by age or sex in this table. Björk-Jarabak proportions are growth-stage sensitive — verify against age-matched source.",
    norms: [
      { label: "Sum of angles", mean: 396, sd: 6, type: "angle" },
      { label: "N-S-Ar", mean: 123, sd: 5, type: "angle" },
      { label: "S-Ar-Go", mean: 143, sd: 6, type: "angle" },
      { label: "Ar-Go-Me", mean: 130, sd: 7, type: "angle" },
      { label: "ML-NSL", mean: 32, sd: 2, type: "angle" },
      { label: "NL-NSL", mean: 8.5, sd: 3, type: "angle" },
    ],
  },
  Tweed: {
    source: "Tweed, 1954",
    population: "Caucasian (North American)",
    ageRange: "Adult",
    sex: "Pooled (male + female)",
    stratification: "Not stratified by age, sex, or ethnicity. Single adult value — do not apply to growing patients.",
    norms: [
      { label: "FMA", mean: 25, sd: 3, type: "angle" },
      { label: "FMIA", mean: 65, sd: 3, type: "angle" },
      { label: "IMPA", mean: 90, sd: 3, type: "angle" },
      { label: "SNA", mean: 82, sd: 2, type: "angle" },
      { label: "SNB", mean: 80, sd: 2, type: "angle" },
      { label: "ANB", mean: 2, sd: 2, type: "angle" },
    ],
  },
  Airway: {
    source: "Composite — McNamara, Riley-Powell, Guilleminault, Solow",
    population: "Mixed populations",
    ageRange: "Adult (default); age-stratified in source",
    sex: "Pooled (male + female)",
    stratification: "Adult norms shown as defaults. Age and sex stratified in source literature — use child/adolescent values for growing patients.",
    norms: [
      { label: "Nasopharynx", mean: 250, sd: 50, type: "area" },
      { label: "Oropharynx", mean: 350, sd: 60, type: "area" },
      { label: "Hypopharynx", mean: 200, sd: 40, type: "area" },
      { label: "PNS-Ad1", mean: 15, sd: 3, type: "length" },
      { label: "SP-Ad2", mean: 11, sd: 3, type: "length" },
      { label: "Vallecula-Ad4", mean: 20, sd: 5, type: "length" },
      { label: "Minimum PAS", mean: 10, sd: 3, type: "length" },
      { label: "PNS-Ad2", mean: 18, sd: 4, type: "length" },
      { label: "UP width", mean: 12, sd: 4, type: "length" },
      { label: "LP width", mean: 18, sd: 5, type: "length" },
      { label: "McUP", mean: 10, sd: 3, type: "length" },
      { label: "McLP", mean: 11, sd: 4, type: "length" },
      { label: "SPAS", mean: 10, sd: 3, type: "length" },
      { label: "MAS", mean: 15, sd: 4, type: "length" },
      { label: "IAS", mean: 12, sd: 4, type: "length" },
      { label: "Vertical Airway Length", mean: 70, sd: 10, type: "length" },
      { label: "Eb-PNS", mean: 65, sd: 10, type: "length" },
      { label: "Angle of Nasopharynx", mean: 140, sd: 10, type: "angle" },
      { label: "Adenoid/Nasopharynx Ratio", mean: 0.5, sd: 0.15, type: "ratio" },
      { label: "R-PAS", mean: 11.2, sd: 2.4, type: "length" },
      { label: "R-RG", mean: 12.5, sd: 2.8, type: "length" },
      { label: "N-PH", mean: 24.3, sd: 3.6, type: "length" },
      { label: "MP-H", mean: 12.3, sd: 3.5, type: "length" },
      { label: "Tongue Length", mean: 76.9, sd: 5.6, type: "length" },
      { label: "Soft Palate Length", mean: 32.4, sd: 3.2, type: "length" },
      { label: "Soft Palate Thickness", mean: 8.5, sd: 1.8, type: "length" },
    ],
  },
};

export const AIRWAY_NORMS = {
  "R-PAS": { mean: 11.2, sd: 2.4, source: "McNamara 1984", note: "Retropalatal airway, narrowest width between soft palate and posterior pharyngeal wall" },
  "R-RG": { mean: 12.5, sd: 2.8, source: "McNamara 1984", note: "Retroglossal airway, narrowest width between tongue base and posterior pharyngeal wall" },
  "N-PH": { mean: 24.3, sd: 3.6, source: "Solow 1985", note: "Nasopharynx depth from PNS to posterior wall" },
  "PNS-AD1": { mean: 15.0, sd: 3.0, source: "Schulhof 1977", note: "Superior airway: PNS to nearest adenoid point" },
  "PNS-AD2": { mean: 18.0, sd: 4.0, source: "Schulhof 1977", note: "Nasopharyngeal depth along Ba-N line" },
  "SPAS": { mean: 10.5, sd: 2.7, source: "Pracharktam 1994", note: "Superior posterior airway space at PNS-Occ level" },
  "MAS": { mean: 9.8, sd: 2.5, source: "Pracharktam 1994", note: "Middle airway space at PNS-Pog' midpoint" },
  "IAS": { mean: 11.6, sd: 3.0, source: "Pracharktam 1994", note: "Inferior airway space at C3-RGN line" },
  "MP-H": { mean: 12.3, sd: 3.5, source: "Bibby 1984", note: "Perpendicular distance from mandibular plane to hyoidale" },
  "Tongue Length": { mean: 76.9, sd: 5.6, source: "Lowe 1985", note: "Distance from tongue tip (TT) to epiglottis base (Eb)" },
  "Soft Palate Length": { mean: 32.4, sd: 3.2, source: "Lowe 1985", note: "Length from PNS to tip of uvula" },
  "Soft Palate Thickness": { mean: 8.5, sd: 1.8, source: "Lowe 1985", note: "Maximum soft palate thickness perpendicular to PNS-P line" },
};
